#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ben
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

packages:
  - nginx
  - r-base
  - rstudio-server

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - apt-get update
  - apt-get install -y gdebi-core
  - wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2024.12.0-467-amd64.deb
  - gdebi --n rstudio-server-2024.12.0-467-amd64.deb
