#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ben
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

packages:
  - nginx
  - r-base
  - rstudio-server

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - apt-get update -y
  - apt-get install -y gdebi-core
  - sudo apt-get -y install libcurl4-gnutls-dev libxml2-dev libssl-dev
  - wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2024.12.0-467-amd64.deb
  - sudo gdebi --n rstudio-server-2024.12.0-467-amd64.deb
  - echo "Installing shiny for R"
  - sudo su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""
  - sudo su - -c "R -e \"install.packages('rmarkdown', repos='http://cran.rstudio.com/')\""  
  - ech "Completed installing shiny for R"
  - wget https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-1.5.22.1017-amd64.deb
  - sudo gdebi --n shiny-server-1.5.22.1017-amd64.deb
  - sudo apt install net-tools -y
  - sudo apt-get install -y git
